import Head from 'next/head'
import apolloClient from '../helpers/apollo'
import { GET_PARENT_PAGES } from '../queries/parentPages'
import HomeBanner from '../components/HomePage/HomeBanner'
import HomePage from '../components/HomePage/HomePage'
import HomeFlexibleService from '../components/HomePage/HomeFlexibleService'
import HomePopularDestinations from '../components/HomePage/HomePopularDestinations'
import HomeFlightManager from '../components/HomePage/HomeFlightManager'
import HomeBookFlight from '../components/HomePage/HomeBookFlight'
import FullBlockRender from '../components/FullBlockRenderer'
export default function Home({homePageData}) {
  console.log(homePageData,"home")
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FullBlockRender blocks={homePageData}/>
       {/* Home Page Section 3 */}
      <section id='home-flexible-service'>
        <HomeFlexibleService/>
      </section>
        {/* Home Page Section 4 */}
        <section id='home-popular-destinations'>
        <HomePopularDestinations/>
      </section>
        {/* Home Page Section 5 */}
        <section id='home-flight-manager'>
        <HomeFlightManager/>
      </section>
         {/* Home Page Section 6 */}
      <section id='home-book-flight'>
        <HomeBookFlight/>
      </section>
    </>
  )
}

export const getStaticProps = async () => {
  let homePageData = null;
  try {
    const{ data } = await apolloClient.query({
      query:GET_PARENT_PAGES,
      variables: 'homepage'
    })
    homePageData = data?.pagesSitemaps?.data[0].attributes.blocks
  } catch (error) {
    console.log(error)
  }
  return{
    props: {
      homePageData
    }
  }
}
