import Head from 'next/head'
import apolloClient from '../helpers/apollo'
import { GET_PARENT_PAGES } from '../queries/parentPages'
import HomeBanner from '../components/HomePage/HomeBanner'
import HomePage from '../components/HomePage/HomePage'
import HomeFlexibleService from '../components/HomePage/HomeFlexibleService'
import HomePopularDestinations from '../components/HomePage/HomePopularDestinations'
import HomeFlightManager from '../components/HomePage/HomeFlightManager'
import HomeBookFlight from '../components/HomePage/HomeBookFlight'
import FullBlockRender from '../components/FullBlockRenderer'
export default function Home({homePageData}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FullBlockRender blocks={homePageData}/>
    </>
  )
}

export const getStaticProps = async () => {
  let homePageData = null;
  try {
    const{ data } = await apolloClient.query({
      query:GET_PARENT_PAGES,
      variables: 'homepage'
    })
    homePageData = data?.pagesSitemaps?.data[0].attributes.blocks
  } catch (error) {
    console.log(error)
  }
  return{
    props: {
      homePageData
    }
  }
}
